title: Generative Music
description: Syllabus for Generative Music Fall 2018
theme: jekyll-theme-minimal

---

Hannah Davis
[http://www.twitter.com/ahandvanish](http://www.twitter.com/ahandvanish)
[http://www.hannahishere.com](http://www.hannahishere.com)