title: Generative Music
description: Syllabus for Generative Music Fall 2018
theme: jekyll-theme-minimal

---

navbar-links:
Twitter: https://twitter.com/ahandvanish
Website: https://www.hannahishere.com